<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['number' => 1, 'name_arabic' => 'الفاتحة', 'name_english' => 'Al-Fatiha', 'total_ayahs' => 7, 'revelation_type' => 'meccan', 'page_start' => 1, 'page_end' => 1, 'juz_start' => 1],
            ['number' => 2, 'name_arabic' => 'البقرة', 'name_english' => 'Al-Baqarah', 'total_ayahs' => 286, 'revelation_type' => 'medinan', 'page_start' => 2, 'page_end' => 49, 'juz_start' => 1],
            ['number' => 3, 'name_arabic' => 'آل عمران', 'name_english' => 'Aal-Imran', 'total_ayahs' => 200, 'revelation_type' => 'medinan', 'page_start' => 50, 'page_end' => 76, 'juz_start' => 3],
            ['number' => 4, 'name_arabic' => 'النساء', 'name_english' => 'An-Nisa', 'total_ayahs' => 176, 'revelation_type' => 'medinan', 'page_start' => 77, 'page_end' => 106, 'juz_start' => 4],
            ['number' => 5, 'name_arabic' => 'المائدة', 'name_english' => 'Al-Maidah', 'total_ayahs' => 120, 'revelation_type' => 'medinan', 'page_start' => 106, 'page_end' => 127, 'juz_start' => 6],
            ['number' => 6, 'name_arabic' => 'الأنعام', 'name_english' => 'Al-Anam', 'total_ayahs' => 165, 'revelation_type' => 'meccan', 'page_start' => 128, 'page_end' => 150, 'juz_start' => 7],
            ['number' => 7, 'name_arabic' => 'الأعراف', 'name_english' => 'Al-Araf', 'total_ayahs' => 206, 'revelation_type' => 'meccan', 'page_start' => 151, 'page_end' => 176, 'juz_start' => 8],
            ['number' => 8, 'name_arabic' => 'الأنفال', 'name_english' => 'Al-Anfal', 'total_ayahs' => 75, 'revelation_type' => 'medinan', 'page_start' => 177, 'page_end' => 186, 'juz_start' => 9],
            ['number' => 9, 'name_arabic' => 'التوبة', 'name_english' => 'At-Tawbah', 'total_ayahs' => 129, 'revelation_type' => 'medinan', 'page_start' => 187, 'page_end' => 207, 'juz_start' => 10],
            ['number' => 10, 'name_arabic' => 'يونس', 'name_english' => 'Yunus', 'total_ayahs' => 109, 'revelation_type' => 'meccan', 'page_start' => 208, 'page_end' => 221, 'juz_start' => 11],
            ['number' => 11, 'name_arabic' => 'هود', 'name_english' => 'Hud', 'total_ayahs' => 123, 'revelation_type' => 'meccan', 'page_start' => 221, 'page_end' => 235, 'juz_start' => 11],
            ['number' => 12, 'name_arabic' => 'يوسف', 'name_english' => 'Yusuf', 'total_ayahs' => 111, 'revelation_type' => 'meccan', 'page_start' => 235, 'page_end' => 248, 'juz_start' => 12],
            ['number' => 13, 'name_arabic' => 'الرعد', 'name_english' => 'Ar-Rad', 'total_ayahs' => 43, 'revelation_type' => 'medinan', 'page_start' => 249, 'page_end' => 255, 'juz_start' => 13],
            ['number' => 14, 'name_arabic' => 'إبراهيم', 'name_english' => 'Ibrahim', 'total_ayahs' => 52, 'revelation_type' => 'meccan', 'page_start' => 255, 'page_end' => 261, 'juz_start' => 13],
            ['number' => 15, 'name_arabic' => 'الحجر', 'name_english' => 'Al-Hijr', 'total_ayahs' => 99, 'revelation_type' => 'meccan', 'page_start' => 262, 'page_end' => 267, 'juz_start' => 14],
            ['number' => 16, 'name_arabic' => 'النحل', 'name_english' => 'An-Nahl', 'total_ayahs' => 128, 'revelation_type' => 'meccan', 'page_start' => 267, 'page_end' => 281, 'juz_start' => 14],
            ['number' => 17, 'name_arabic' => 'الإسراء', 'name_english' => 'Al-Isra', 'total_ayahs' => 111, 'revelation_type' => 'meccan', 'page_start' => 282, 'page_end' => 293, 'juz_start' => 15],
            ['number' => 18, 'name_arabic' => 'الكهف', 'name_english' => 'Al-Kahf', 'total_ayahs' => 110, 'revelation_type' => 'meccan', 'page_start' => 293, 'page_end' => 304, 'juz_start' => 15],
            ['number' => 19, 'name_arabic' => 'مريم', 'name_english' => 'Maryam', 'total_ayahs' => 98, 'revelation_type' => 'meccan', 'page_start' => 305, 'page_end' => 312, 'juz_start' => 16],
            ['number' => 20, 'name_arabic' => 'طه', 'name_english' => 'Ta-Ha', 'total_ayahs' => 135, 'revelation_type' => 'meccan', 'page_start' => 312, 'page_end' => 321, 'juz_start' => 16],
            ['number' => 21, 'name_arabic' => 'الأنبياء', 'name_english' => 'Al-Anbiya', 'total_ayahs' => 112, 'revelation_type' => 'meccan', 'page_start' => 322, 'page_end' => 331, 'juz_start' => 17],
            ['number' => 22, 'name_arabic' => 'الحج', 'name_english' => 'Al-Hajj', 'total_ayahs' => 78, 'revelation_type' => 'medinan', 'page_start' => 332, 'page_end' => 341, 'juz_start' => 17],
            ['number' => 23, 'name_arabic' => 'المؤمنون', 'name_english' => 'Al-Muminun', 'total_ayahs' => 118, 'revelation_type' => 'meccan', 'page_start' => 342, 'page_end' => 349, 'juz_start' => 18],
            ['number' => 24, 'name_arabic' => 'النور', 'name_english' => 'An-Nur', 'total_ayahs' => 64, 'revelation_type' => 'medinan', 'page_start' => 350, 'page_end' => 359, 'juz_start' => 18],
            ['number' => 25, 'name_arabic' => 'الفرقان', 'name_english' => 'Al-Furqan', 'total_ayahs' => 77, 'revelation_type' => 'meccan', 'page_start' => 359, 'page_end' => 366, 'juz_start' => 18],
            ['number' => 26, 'name_arabic' => 'الشعراء', 'name_english' => 'Ash-Shuara', 'total_ayahs' => 227, 'revelation_type' => 'meccan', 'page_start' => 367, 'page_end' => 376, 'juz_start' => 19],
            ['number' => 27, 'name_arabic' => 'النمل', 'name_english' => 'An-Naml', 'total_ayahs' => 93, 'revelation_type' => 'meccan', 'page_start' => 377, 'page_end' => 385, 'juz_start' => 19],
            ['number' => 28, 'name_arabic' => 'القصص', 'name_english' => 'Al-Qasas', 'total_ayahs' => 88, 'revelation_type' => 'meccan', 'page_start' => 385, 'page_end' => 396, 'juz_start' => 20],
            ['number' => 29, 'name_arabic' => 'العنكبوت', 'name_english' => 'Al-Ankabut', 'total_ayahs' => 69, 'revelation_type' => 'meccan', 'page_start' => 396, 'page_end' => 404, 'juz_start' => 20],
            ['number' => 30, 'name_arabic' => 'الروم', 'name_english' => 'Ar-Rum', 'total_ayahs' => 60, 'revelation_type' => 'meccan', 'page_start' => 404, 'page_end' => 410, 'juz_start' => 21],
            ['number' => 31, 'name_arabic' => 'لقمان', 'name_english' => 'Luqman', 'total_ayahs' => 34, 'revelation_type' => 'meccan', 'page_start' => 411, 'page_end' => 414, 'juz_start' => 21],
            ['number' => 32, 'name_arabic' => 'السجدة', 'name_english' => 'As-Sajdah', 'total_ayahs' => 30, 'revelation_type' => 'meccan', 'page_start' => 415, 'page_end' => 417, 'juz_start' => 21],
            ['number' => 33, 'name_arabic' => 'الأحزاب', 'name_english' => 'Al-Ahzab', 'total_ayahs' => 73, 'revelation_type' => 'medinan', 'page_start' => 418, 'page_end' => 427, 'juz_start' => 21],
            ['number' => 34, 'name_arabic' => 'سبأ', 'name_english' => 'Saba', 'total_ayahs' => 54, 'revelation_type' => 'meccan', 'page_start' => 428, 'page_end' => 434, 'juz_start' => 22],
            ['number' => 35, 'name_arabic' => 'فاطر', 'name_english' => 'Fatir', 'total_ayahs' => 45, 'revelation_type' => 'meccan', 'page_start' => 434, 'page_end' => 440, 'juz_start' => 22],
            ['number' => 36, 'name_arabic' => 'يس', 'name_english' => 'Ya-Sin', 'total_ayahs' => 83, 'revelation_type' => 'meccan', 'page_start' => 440, 'page_end' => 445, 'juz_start' => 22],
            ['number' => 37, 'name_arabic' => 'الصافات', 'name_english' => 'As-Saffat', 'total_ayahs' => 182, 'revelation_type' => 'meccan', 'page_start' => 446, 'page_end' => 452, 'juz_start' => 23],
            ['number' => 38, 'name_arabic' => 'ص', 'name_english' => 'Sad', 'total_ayahs' => 88, 'revelation_type' => 'meccan', 'page_start' => 453, 'page_end' => 458, 'juz_start' => 23],
            ['number' => 39, 'name_arabic' => 'الزمر', 'name_english' => 'Az-Zumar', 'total_ayahs' => 75, 'revelation_type' => 'meccan', 'page_start' => 458, 'page_end' => 467, 'juz_start' => 23],
            ['number' => 40, 'name_arabic' => 'غافر', 'name_english' => 'Ghafir', 'total_ayahs' => 85, 'revelation_type' => 'meccan', 'page_start' => 467, 'page_end' => 476, 'juz_start' => 24],
            ['number' => 41, 'name_arabic' => 'فصلت', 'name_english' => 'Fussilat', 'total_ayahs' => 54, 'revelation_type' => 'meccan', 'page_start' => 477, 'page_end' => 482, 'juz_start' => 24],
            ['number' => 42, 'name_arabic' => 'الشورى', 'name_english' => 'Ash-Shura', 'total_ayahs' => 53, 'revelation_type' => 'meccan', 'page_start' => 483, 'page_end' => 489, 'juz_start' => 25],
            ['number' => 43, 'name_arabic' => 'الزخرف', 'name_english' => 'Az-Zukhruf', 'total_ayahs' => 89, 'revelation_type' => 'meccan', 'page_start' => 489, 'page_end' => 495, 'juz_start' => 25],
            ['number' => 44, 'name_arabic' => 'الدخان', 'name_english' => 'Ad-Dukhan', 'total_ayahs' => 59, 'revelation_type' => 'meccan', 'page_start' => 496, 'page_end' => 498, 'juz_start' => 25],
            ['number' => 45, 'name_arabic' => 'الجاثية', 'name_english' => 'Al-Jathiyah', 'total_ayahs' => 37, 'revelation_type' => 'meccan', 'page_start' => 499, 'page_end' => 502, 'juz_start' => 25],
            ['number' => 46, 'name_arabic' => 'الأحقاف', 'name_english' => 'Al-Ahqaf', 'total_ayahs' => 35, 'revelation_type' => 'meccan', 'page_start' => 502, 'page_end' => 506, 'juz_start' => 26],
            ['number' => 47, 'name_arabic' => 'محمد', 'name_english' => 'Muhammad', 'total_ayahs' => 38, 'revelation_type' => 'medinan', 'page_start' => 507, 'page_end' => 510, 'juz_start' => 26],
            ['number' => 48, 'name_arabic' => 'الفتح', 'name_english' => 'Al-Fath', 'total_ayahs' => 29, 'revelation_type' => 'medinan', 'page_start' => 511, 'page_end' => 515, 'juz_start' => 26],
            ['number' => 49, 'name_arabic' => 'الحجرات', 'name_english' => 'Al-Hujurat', 'total_ayahs' => 18, 'revelation_type' => 'medinan', 'page_start' => 515, 'page_end' => 517, 'juz_start' => 26],
            ['number' => 50, 'name_arabic' => 'ق', 'name_english' => 'Qaf', 'total_ayahs' => 45, 'revelation_type' => 'meccan', 'page_start' => 518, 'page_end' => 520, 'juz_start' => 26],
            ['number' => 51, 'name_arabic' => 'الذاريات', 'name_english' => 'Adh-Dhariyat', 'total_ayahs' => 60, 'revelation_type' => 'meccan', 'page_start' => 520, 'page_end' => 523, 'juz_start' => 26],
            ['number' => 52, 'name_arabic' => 'الطور', 'name_english' => 'At-Tur', 'total_ayahs' => 49, 'revelation_type' => 'meccan', 'page_start' => 523, 'page_end' => 525, 'juz_start' => 27],
            ['number' => 53, 'name_arabic' => 'النجم', 'name_english' => 'An-Najm', 'total_ayahs' => 62, 'revelation_type' => 'meccan', 'page_start' => 526, 'page_end' => 528, 'juz_start' => 27],
            ['number' => 54, 'name_arabic' => 'القمر', 'name_english' => 'Al-Qamar', 'total_ayahs' => 55, 'revelation_type' => 'meccan', 'page_start' => 528, 'page_end' => 531, 'juz_start' => 27],
            ['number' => 55, 'name_arabic' => 'الرحمن', 'name_english' => 'Ar-Rahman', 'total_ayahs' => 78, 'revelation_type' => 'medinan', 'page_start' => 531, 'page_end' => 534, 'juz_start' => 27],
            ['number' => 56, 'name_arabic' => 'الواقعة', 'name_english' => 'Al-Waqiah', 'total_ayahs' => 96, 'revelation_type' => 'meccan', 'page_start' => 534, 'page_end' => 537, 'juz_start' => 27],
            ['number' => 57, 'name_arabic' => 'الحديد', 'name_english' => 'Al-Hadid', 'total_ayahs' => 29, 'revelation_type' => 'medinan', 'page_start' => 537, 'page_end' => 541, 'juz_start' => 27],
            ['number' => 58, 'name_arabic' => 'المجادلة', 'name_english' => 'Al-Mujadila', 'total_ayahs' => 22, 'revelation_type' => 'medinan', 'page_start' => 542, 'page_end' => 545, 'juz_start' => 28],
            ['number' => 59, 'name_arabic' => 'الحشر', 'name_english' => 'Al-Hashr', 'total_ayahs' => 24, 'revelation_type' => 'medinan', 'page_start' => 545, 'page_end' => 548, 'juz_start' => 28],
            ['number' => 60, 'name_arabic' => 'الممتحنة', 'name_english' => 'Al-Mumtahanah', 'total_ayahs' => 13, 'revelation_type' => 'medinan', 'page_start' => 549, 'page_end' => 551, 'juz_start' => 28],
            ['number' => 61, 'name_arabic' => 'الصف', 'name_english' => 'As-Saf', 'total_ayahs' => 14, 'revelation_type' => 'medinan', 'page_start' => 551, 'page_end' => 552, 'juz_start' => 28],
            ['number' => 62, 'name_arabic' => 'الجمعة', 'name_english' => 'Al-Jumuah', 'total_ayahs' => 11, 'revelation_type' => 'medinan', 'page_start' => 553, 'page_end' => 554, 'juz_start' => 28],
            ['number' => 63, 'name_arabic' => 'المنافقون', 'name_english' => 'Al-Munafiqun', 'total_ayahs' => 11, 'revelation_type' => 'medinan', 'page_start' => 554, 'page_end' => 555, 'juz_start' => 28],
            ['number' => 64, 'name_arabic' => 'التغابن', 'name_english' => 'At-Taghabun', 'total_ayahs' => 18, 'revelation_type' => 'medinan', 'page_start' => 556, 'page_end' => 557, 'juz_start' => 28],
            ['number' => 65, 'name_arabic' => 'الطلاق', 'name_english' => 'At-Talaq', 'total_ayahs' => 12, 'revelation_type' => 'medinan', 'page_start' => 558, 'page_end' => 559, 'juz_start' => 28],
            ['number' => 66, 'name_arabic' => 'التحريم', 'name_english' => 'At-Tahrim', 'total_ayahs' => 12, 'revelation_type' => 'medinan', 'page_start' => 560, 'page_end' => 561, 'juz_start' => 28],
            ['number' => 67, 'name_arabic' => 'الملك', 'name_english' => 'Al-Mulk', 'total_ayahs' => 30, 'revelation_type' => 'meccan', 'page_start' => 562, 'page_end' => 564, 'juz_start' => 29],
            ['number' => 68, 'name_arabic' => 'القلم', 'name_english' => 'Al-Qalam', 'total_ayahs' => 52, 'revelation_type' => 'meccan', 'page_start' => 564, 'page_end' => 566, 'juz_start' => 29],
            ['number' => 69, 'name_arabic' => 'الحاقة', 'name_english' => 'Al-Haqqah', 'total_ayahs' => 52, 'revelation_type' => 'meccan', 'page_start' => 566, 'page_end' => 568, 'juz_start' => 29],
            ['number' => 70, 'name_arabic' => 'المعارج', 'name_english' => 'Al-Maarij', 'total_ayahs' => 44, 'revelation_type' => 'meccan', 'page_start' => 568, 'page_end' => 570, 'juz_start' => 29],
            ['number' => 71, 'name_arabic' => 'نوح', 'name_english' => 'Nuh', 'total_ayahs' => 28, 'revelation_type' => 'meccan', 'page_start' => 570, 'page_end' => 571, 'juz_start' => 29],
            ['number' => 72, 'name_arabic' => 'الجن', 'name_english' => 'Al-Jinn', 'total_ayahs' => 28, 'revelation_type' => 'meccan', 'page_start' => 572, 'page_end' => 573, 'juz_start' => 29],
            ['number' => 73, 'name_arabic' => 'المزمل', 'name_english' => 'Al-Muzzammil', 'total_ayahs' => 20, 'revelation_type' => 'meccan', 'page_start' => 574, 'page_end' => 575, 'juz_start' => 29],
            ['number' => 74, 'name_arabic' => 'المدثر', 'name_english' => 'Al-Muddaththir', 'total_ayahs' => 56, 'revelation_type' => 'meccan', 'page_start' => 575, 'page_end' => 577, 'juz_start' => 29],
            ['number' => 75, 'name_arabic' => 'القيامة', 'name_english' => 'Al-Qiyamah', 'total_ayahs' => 40, 'revelation_type' => 'meccan', 'page_start' => 577, 'page_end' => 578, 'juz_start' => 29],
            ['number' => 76, 'name_arabic' => 'الإنسان', 'name_english' => 'Al-Insan', 'total_ayahs' => 31, 'revelation_type' => 'medinan', 'page_start' => 578, 'page_end' => 580, 'juz_start' => 29],
            ['number' => 77, 'name_arabic' => 'المرسلات', 'name_english' => 'Al-Mursalat', 'total_ayahs' => 50, 'revelation_type' => 'meccan', 'page_start' => 580, 'page_end' => 581, 'juz_start' => 29],
            ['number' => 78, 'name_arabic' => 'النبأ', 'name_english' => 'An-Naba', 'total_ayahs' => 40, 'revelation_type' => 'meccan', 'page_start' => 582, 'page_end' => 583, 'juz_start' => 30],
            ['number' => 79, 'name_arabic' => 'النازعات', 'name_english' => 'An-Naziat', 'total_ayahs' => 46, 'revelation_type' => 'meccan', 'page_start' => 583, 'page_end' => 584, 'juz_start' => 30],
            ['number' => 80, 'name_arabic' => 'عبس', 'name_english' => 'Abasa', 'total_ayahs' => 42, 'revelation_type' => 'meccan', 'page_start' => 585, 'page_end' => 586, 'juz_start' => 30],
            ['number' => 81, 'name_arabic' => 'التكوير', 'name_english' => 'At-Takwir', 'total_ayahs' => 29, 'revelation_type' => 'meccan', 'page_start' => 586, 'page_end' => 586, 'juz_start' => 30],
            ['number' => 82, 'name_arabic' => 'الانفطار', 'name_english' => 'Al-Infitar', 'total_ayahs' => 19, 'revelation_type' => 'meccan', 'page_start' => 587, 'page_end' => 587, 'juz_start' => 30],
            ['number' => 83, 'name_arabic' => 'المطففين', 'name_english' => 'Al-Mutaffifin', 'total_ayahs' => 36, 'revelation_type' => 'meccan', 'page_start' => 587, 'page_end' => 589, 'juz_start' => 30],
            ['number' => 84, 'name_arabic' => 'الانشقاق', 'name_english' => 'Al-Inshiqaq', 'total_ayahs' => 25, 'revelation_type' => 'meccan', 'page_start' => 589, 'page_end' => 589, 'juz_start' => 30],
            ['number' => 85, 'name_arabic' => 'البروج', 'name_english' => 'Al-Buruj', 'total_ayahs' => 22, 'revelation_type' => 'meccan', 'page_start' => 590, 'page_end' => 590, 'juz_start' => 30],
            ['number' => 86, 'name_arabic' => 'الطارق', 'name_english' => 'At-Tariq', 'total_ayahs' => 17, 'revelation_type' => 'meccan', 'page_start' => 591, 'page_end' => 591, 'juz_start' => 30],
            ['number' => 87, 'name_arabic' => 'الأعلى', 'name_english' => 'Al-Ala', 'total_ayahs' => 19, 'revelation_type' => 'meccan', 'page_start' => 591, 'page_end' => 592, 'juz_start' => 30],
            ['number' => 88, 'name_arabic' => 'الغاشية', 'name_english' => 'Al-Ghashiyah', 'total_ayahs' => 26, 'revelation_type' => 'meccan', 'page_start' => 592, 'page_end' => 592, 'juz_start' => 30],
            ['number' => 89, 'name_arabic' => 'الفجر', 'name_english' => 'Al-Fajr', 'total_ayahs' => 30, 'revelation_type' => 'meccan', 'page_start' => 593, 'page_end' => 594, 'juz_start' => 30],
            ['number' => 90, 'name_arabic' => 'البلد', 'name_english' => 'Al-Balad', 'total_ayahs' => 20, 'revelation_type' => 'meccan', 'page_start' => 594, 'page_end' => 594, 'juz_start' => 30],
            ['number' => 91, 'name_arabic' => 'الشمس', 'name_english' => 'Ash-Shams', 'total_ayahs' => 15, 'revelation_type' => 'meccan', 'page_start' => 595, 'page_end' => 595, 'juz_start' => 30],
            ['number' => 92, 'name_arabic' => 'الليل', 'name_english' => 'Al-Layl', 'total_ayahs' => 21, 'revelation_type' => 'meccan', 'page_start' => 595, 'page_end' => 596, 'juz_start' => 30],
            ['number' => 93, 'name_arabic' => 'الضحى', 'name_english' => 'Ad-Duha', 'total_ayahs' => 11, 'revelation_type' => 'meccan', 'page_start' => 596, 'page_end' => 596, 'juz_start' => 30],
            ['number' => 94, 'name_arabic' => 'الشرح', 'name_english' => 'Ash-Sharh', 'total_ayahs' => 8, 'revelation_type' => 'meccan', 'page_start' => 596, 'page_end' => 596, 'juz_start' => 30],
            ['number' => 95, 'name_arabic' => 'التين', 'name_english' => 'At-Tin', 'total_ayahs' => 8, 'revelation_type' => 'meccan', 'page_start' => 597, 'page_end' => 597, 'juz_start' => 30],
            ['number' => 96, 'name_arabic' => 'العلق', 'name_english' => 'Al-Alaq', 'total_ayahs' => 19, 'revelation_type' => 'meccan', 'page_start' => 597, 'page_end' => 597, 'juz_start' => 30],
            ['number' => 97, 'name_arabic' => 'القدر', 'name_english' => 'Al-Qadr', 'total_ayahs' => 5, 'revelation_type' => 'meccan', 'page_start' => 598, 'page_end' => 598, 'juz_start' => 30],
            ['number' => 98, 'name_arabic' => 'البينة', 'name_english' => 'Al-Bayyinah', 'total_ayahs' => 8, 'revelation_type' => 'medinan', 'page_start' => 598, 'page_end' => 599, 'juz_start' => 30],
            ['number' => 99, 'name_arabic' => 'الزلزلة', 'name_english' => 'Az-Zalzalah', 'total_ayahs' => 8, 'revelation_type' => 'medinan', 'page_start' => 599, 'page_end' => 599, 'juz_start' => 30],
            ['number' => 100, 'name_arabic' => 'العاديات', 'name_english' => 'Al-Adiyat', 'total_ayahs' => 11, 'revelation_type' => 'meccan', 'page_start' => 599, 'page_end' => 600, 'juz_start' => 30],
            ['number' => 101, 'name_arabic' => 'القارعة', 'name_english' => 'Al-Qariah', 'total_ayahs' => 11, 'revelation_type' => 'meccan', 'page_start' => 600, 'page_end' => 600, 'juz_start' => 30],
            ['number' => 102, 'name_arabic' => 'التكاثر', 'name_english' => 'At-Takathur', 'total_ayahs' => 8, 'revelation_type' => 'meccan', 'page_start' => 600, 'page_end' => 600, 'juz_start' => 30],
            ['number' => 103, 'name_arabic' => 'العصر', 'name_english' => 'Al-Asr', 'total_ayahs' => 3, 'revelation_type' => 'meccan', 'page_start' => 601, 'page_end' => 601, 'juz_start' => 30],
            ['number' => 104, 'name_arabic' => 'الهمزة', 'name_english' => 'Al-Humazah', 'total_ayahs' => 9, 'revelation_type' => 'meccan', 'page_start' => 601, 'page_end' => 601, 'juz_start' => 30],
            ['number' => 105, 'name_arabic' => 'الفيل', 'name_english' => 'Al-Fil', 'total_ayahs' => 5, 'revelation_type' => 'meccan', 'page_start' => 601, 'page_end' => 601, 'juz_start' => 30],
            ['number' => 106, 'name_arabic' => 'قريش', 'name_english' => 'Quraysh', 'total_ayahs' => 4, 'revelation_type' => 'meccan', 'page_start' => 602, 'page_end' => 602, 'juz_start' => 30],
            ['number' => 107, 'name_arabic' => 'الماعون', 'name_english' => 'Al-Maun', 'total_ayahs' => 7, 'revelation_type' => 'meccan', 'page_start' => 602, 'page_end' => 602, 'juz_start' => 30],
            ['number' => 108, 'name_arabic' => 'الكوثر', 'name_english' => 'Al-Kawthar', 'total_ayahs' => 3, 'revelation_type' => 'meccan', 'page_start' => 602, 'page_end' => 602, 'juz_start' => 30],
            ['number' => 109, 'name_arabic' => 'الكافرون', 'name_english' => 'Al-Kafirun', 'total_ayahs' => 6, 'revelation_type' => 'meccan', 'page_start' => 603, 'page_end' => 603, 'juz_start' => 30],
            ['number' => 110, 'name_arabic' => 'النصر', 'name_english' => 'An-Nasr', 'total_ayahs' => 3, 'revelation_type' => 'medinan', 'page_start' => 603, 'page_end' => 603, 'juz_start' => 30],
            ['number' => 111, 'name_arabic' => 'المسد', 'name_english' => 'Al-Masad', 'total_ayahs' => 5, 'revelation_type' => 'meccan', 'page_start' => 603, 'page_end' => 603, 'juz_start' => 30],
            ['number' => 112, 'name_arabic' => 'الإخلاص', 'name_english' => 'Al-Ikhlas', 'total_ayahs' => 4, 'revelation_type' => 'meccan', 'page_start' => 604, 'page_end' => 604, 'juz_start' => 30],
            ['number' => 113, 'name_arabic' => 'الفلق', 'name_english' => 'Al-Falaq', 'total_ayahs' => 5, 'revelation_type' => 'meccan', 'page_start' => 604, 'page_end' => 604, 'juz_start' => 30],
            ['number' => 114, 'name_arabic' => 'الناس', 'name_english' => 'An-Nas', 'total_ayahs' => 6, 'revelation_type' => 'meccan', 'page_start' => 604, 'page_end' => 604, 'juz_start' => 30],
        ];

        foreach ($surahs as $surah) {
            Surah::create($surah);
        }

        $this->command->info('✅ تم إنشاء 114 سورة بنجاح');
    }
}